name: Docc

on:
  workflow_call:
    inputs:
      project_target:
        required: true
        type: string
      hosting_path:
        required: true
        type: string

  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: docs-out

      - name: View Swift Version
        run: swift --version

      - name: Build documentation
        run: >
          rm -rf docs-out/.git;
          rm -rf docs-out/main;
          rm -rf docs-out/latest;
          for tag in $(echo "main"; echo "latest"; git tag | tail -n +94);
          do
            echo "⏳ Generating documentation for "$tag" release.";
            
            if [ -d "docs-out/$tag" ]
            then
                echo "✅ Documentation for "$tag" already exists.";
            else
                if [ "$tag" == "latest" ]; then
                  git checkout -f "$(git tag | tail -n 1)";
                else
                  git checkout -f "$tag";
                fi
                
                swift package \
                --allow-writing-to-directory docs-out/"$tag" \
                generate-documentation \
                --target ${{ inputs.project_target }} \
                --output-path docs-out/"$tag" \
                --transform-for-static-hosting \
                --hosting-base-path /${{ inputs.hosting_path }}/"$tag" \
                    && echo "✅ Documentation generated for "$tag" release." \
                    || echo "⚠️ Documentation skipped for "$tag".";
            fi;
          done
      
      - name: Fix permissions
        run: 'sudo chown -R $USER docs-out'

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
